### ISSUE TITLE
JSON Export issue

### ISSUE THREAD

**Issue by JimChen** [kiote/activeadmin-poro-decorator#5]
Thank you for making this awesome plugin for activeadmin.  We got an error when using the json download link. Here is the detail info:
2019-03-19 00:33:38.262 [fyi] Completed 500 Internal Server Error in 23ms (ActiveRecord: 1.5ms) (pid:33006)
2019-03-19 00:33:38.263 [omg]  (pid:33006)
2019-03-19 00:33:38.263 [omg] NoMethodError (undefined method `demodulize' for nil:NilClass): (pid:33006)
2019-03-19 00:33:38.264 [omg]  (pid:33006)
2019-03-19 00:33:38.264 [omg] active_model_serializers (0.10.9) lib/active_model_serializers/lookup_chain.rb:70:in `resource_class_name'
active_model_serializers (0.10.9) lib/active_model_serializers/lookup_chain.rb:29:in `block in <module:LookupChain>'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:69:in `block in serializer_lookup_chain_for'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:68:in `each'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:68:in `flat_map'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:68:in `serializer_lookup_chain_for'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:91:in `block in get_serializer_for'
thread_safe (0.3.6) lib/thread_safe/cache.rb:66:in `block in fetch_or_store'
thread_safe (0.3.6) lib/thread_safe/cache.rb:56:in `fetch'
thread_safe (0.3.6) lib/thread_safe/cache.rb:65:in `fetch_or_store'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:89:in `get_serializer_for'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:97:in `block in get_serializer_for'
thread_safe (0.3.6) lib/thread_safe/cache.rb:66:in `block in fetch_or_store'
thread_safe (0.3.6) lib/thread_safe/cache.rb:56:in `fetch'
thread_safe (0.3.6) lib/thread_safe/cache.rb:65:in `fetch_or_store'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:89:in `get_serializer_for'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:51:in `block in serializer_for'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:51:in `fetch'
active_model_serializers (0.10.9) lib/active_model/serializer.rb:51:in `serializer_for'
active_model_serializers (0.10.9) lib/active_model/serializer/collection_serializer.rb:78:in `block in serializer_from_resource'
active_model_serializers (0.10.9) lib/active_model/serializer/collection_serializer.rb:77:in `fetch'
active_model_serializers (0.10.9) lib/active_model/serializer/collection_serializer.rb:77:in `serializer_from_resource'
active_model_serializers (0.10.9) lib/active_model/serializer/collection_serializer.rb:72:in `block in serializers_from_resources'
activeadmin-poro-decorator (0.2.0) lib/activeadmin-poro-decorator.rb:68:in `map'
activeadmin-poro-decorator (0.2.0) lib/activeadmin-poro-decorator.rb:68:in `map'
active_model_serializers (0.10.9) lib/active_model/serializer/collection_serializer.rb:71:in `serializers_from_resources'
active_model_serializers (0.10.9) lib/active_model/serializer/collection_serializer.rb:15:in `initialize'
active_model_serializers (0.10.9) lib/active_model_serializers/serializable_resource.rb:50:in `new'
active_model_serializers (0.10.9) lib/active_model_serializers/serializable_resource.rb:50:in `serializer_instance'
active_model_serializers (0.10.9) lib/active_model_serializers/serializable_resource.rb:44:in `block in find_adapter'
active_model_serializers (0.10.9) lib/active_model_serializers/serializable_resource.rb:43:in `catch'
active_model_serializers (0.10.9) lib/active_model_serializers/serializable_resource.rb:43:in `find_adapter'
active_model_serializers (0.10.9) lib/active_model_serializers/serializable_resource.rb:37:in `adapter'
active_model_serializers (0.10.9) lib/action_controller/serialization.rb:50:in `get_serializer'
active_model_serializers (0.10.9) lib/action_controller/serialization.rb:63:in `block (2 levels) in <module:Serialization>'
actionpack (5.2.2) lib/action_controller/metal/renderers.rb:150:in `block in _render_to_body_with_renderer'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/2.6.0/set.rb:338:in `each_key'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/2.6.0/set.rb:338:in `each'
actionpack (5.2.2) lib/action_controller/metal/renderers.rb:146:in `_render_to_body_with_renderer'
actionpack (5.2.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (5.2.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (5.2.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
activesupport (5.2.2) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
activesupport (5.2.2) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.2.2) lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:45:in `render'
meta-tags (2.11.1) lib/meta_tags/controller_helper.rb:22:in `render'
responders (2.4.1) lib/action_controller/responder.rb:260:in `display'
responders (2.4.1) lib/action_controller/responder.rb:214:in `api_behavior'
responders (2.4.1) lib/action_controller/responder.rb:193:in `rescue in to_format'
responders (2.4.1) lib/action_controller/responder.rb:184:in `to_format'
responders (2.4.1) lib/action_controller/responder.rb:163:in `respond'
responders (2.4.1) lib/action_controller/responder.rb:156:in `call'
responders (2.4.1) lib/action_controller/respond_with.rb:211:in `respond_with'
inherited_resources (1.9.0) lib/inherited_resources/actions.rb:7:in `index'
/usr/local/var/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/bundler/gems/activeadmin-9ea8e2606556/lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (5.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.2) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.2) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.2) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.2) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.2) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.2) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.2) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.2) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.2) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread' (pid:33006)

I'm looking into this.

**Comment by rogerkk** [comment]
Just in case you (or anyone else) stumble across this, then ActiveAdmin relatively recently merged [a PR that added PORO decorator support into AA itself](https://github.com/activeadmin/activeadmin/pull/6249#event-3527194643).

@kiote 's gem has been long lived and done it's job well for a very long time, though. :D
